import type { ExperienceDataType, MenuItemType, PagesListType, ProjectDataType, SocialListType } from "@/types/Content";

export const menuItem: MenuItemType[] = [
  {
    name: "Home",
    icon: "home",
    pathname: ["/", "/about"],
  },
  {
    name: "Experiences",
    icon: "skills",
    pathname: ["/experience"],
  },
  {
    name: "Skills",
    icon: "stack",
    pathname: ["/skills"],
  },
  {
    name: "Projects",
    icon: "project",
    pathname: ["/project"],
  },
  {
    name: "Blog",
    icon: "blog",
    pathname: ["/blog"],
  },
  {
    name: "Contact",
    icon: "contact",
    pathname: ["/contact"],
  },
];

export const pagesList: PagesListType[] = [
  {
    number: "01.",
    label: "Home",
    link: "/",
  },
  {
    number: "02.",
    label: "About",
    link: "/about",
  },
  {
    number: "03.",
    label: "Experiences",
    link: "/experience",
  },
  {
    number: "04.",
    label: "Skills",
    link: "/skills",
  },
  {
    number: "05.",
    label: "Projects",
    link: "/projects",
  },
  {
    number: "06.",
    label: "Blogs",
    link: "/blog",
  },
  {
    number: "07.",
    label: "Games",
    link: "/games",
  },
  {
    number: "08.",
    label: "Contacts",
    link: "/contact",
  }
]

export const workData: ExperienceDataType[] = [
  {
    position: "Front-end Developer",
    company: "Itsavirus",
    place: "Denpasar, Bali - Indonesia",
    start: "July 2023",
  },
  {
    position: "Full-stack Developer",
    company: "LnData Indonesia",
    place: "Surabaya, East Java - Indonesia",
    start: "September 2022",
    end: "April 2023",
  },
  {
    position: "Engineer Intern",
    company: "Unilever Indonesia",
    place: "Surabaya, East Java - Indonesia",
    start: "August 2022",
    end: "September 2022",
  },
  {
    position: "Mobile Development Cohort",
    company: "Bangkit Academy 2022",
    place: "Surabaya, East Java - Indonesia",
    start: "February 2022",
    end: "July 2022",
  },
  {
    position: "Founder & Full-stack Developer",
    company: "Breakpoint Indonesia",
    place: "Surabaya, East Java - Indonesia",
    start: "May 2021",
    end: "February 2023",
  },
  {
    position: "Team Coach Extracurricular",
    company: "SMAN 1 Sidoarjo",
    place: "Sidoarjo, East Java - Indonesia",
    start: "January 2020",
    end: "August 2023",
  },
];

export const organizationData: ExperienceDataType[] = [
  {
    position: "Coordinator of Laboratory Assistant",
    company: "Embedded and Cyber-Physical System",
    place: "Surabaya, East Java - Indonesia",
    start: "March 2022",
    end:"February 2023"
  },
  {
    position: "Coordinator of Web Development",
    company: "Petrolida 2022",
    place: "Surabaya, East Java - Indonesia",
    start: "November 2021",
    end: "May 2022",
  },
  {
    position: "IT Manager",
    company: "Engineering Physics Week 2022",
    place: "Surabaya, East Java - Indonesia",
    start: "October 2021",
    end: "February 2022",
  },
  {
    position: "Head of Web Development",
    company: "Society of Petroleum Engineer ITS",
    place: "Surabaya, East Java - Indonesia",
    start: "August 2021",
    end: "June 2022",
  },
  {
    position: "Expert Staff of Web Development",
    company: "Gerigi ITS 2021",
    place: "Surabaya, East Java - Indonesia",
    start: "July 2021",
    end: "August 2021",
  },
  {
    position: "Staff of IT Developer",
    company: "Ini Lho ITS! 2021",
    place: "Surabaya, East Java - Indonesia",
    start: "December 2020",
    end: "March 2021",
  },
];

export const projectData: ProjectDataType[] = [
  {
    key: "dafkur2.0",
    shape: "horizontal",
    name: "Dafkur.com 2.0",
    description: "My second version of Personal Website",
    tech: ["React", "Bootstrap", "SCSS"],
    logo: null,
    image: "dafkur2.png",
    background: null,
    link: "https://v2.dafkur.com/",
  },
  {
    key: "ifem",
    shape: "vertical",
    name: "IFEM 2022",
    description: "Biggest Mechanical Engineering ITS Event.",
    tech: ["Laravel", "Bootstrap", "SCSS"],
    logo: null,
    image: "ifem.png",
    background: null,
    link: null,
  },
  {
    key: "breakpoint",
    shape: "box",
    name: "Breakpoint",
    description: "My Startup Company Profile.",
    tech: ["Laravel", "Bootstrap", "SCSS"],
    logo: "breakpoint.png",
    image: null,
    background: "#0C1523",
    link: null,
  },
  {
    key: "petrolida",
    shape: "vertical",
    name: "Petrolida 2022",
    description: "Biggest Events by SPE ITS.",
    tech: ["React", "Bootstrap", "Laravel"],
    logo: null,
    image: "petrolida.png",
    background: null,
    link: null,
  },
  {
    key: "candlecraft",
    shape: "box",
    name: "Candle Craft",
    description: "Candle Exporter Product Website.",
    tech: ["Next.js", "Bootstrap", "SCSS"],
    logo: "candlecraft.png",
    image: null,
    background: "#05060A",
    link: "https://candlecraft.co.id/",
  },
  {
    key: "ecs",
    shape: "box",
    name: "ECS Training",
    description: "Programming Training by ECS Laboratory.",
    tech: ["Laravel", "Bootstrap", "SCSS"],
    logo: "ecs.png",
    image: null,
    background: "#E0D6B6",
    link: null,
  },
  {
    key: "spe",
    shape: "box",
    name: "SPE ITS",
    description: "Society of Petroleum Engineers ITS.",
    tech: ["Laravel", "Bootstrap", "SCSS"],
    logo: "spe.png",
    image: null,
    background: "#111840",
    link: null,
  },
  {
    key: "crawlerhub",
    shape: "horizontal",
    name: "Crawlerhub",
    description: "Web Crawler by LnData Indonesia.",
    tech: ["React", "AntDesign", "SCSS"],
    logo: null,
    image: "crawlerhub.png",
    background: null,
    link: "https://crawlerhub.lndata.com/",
  },
  {
    key: "epw",
    shape: "box",
    name: "EPW ITS 2022",
    description: "Biggest Engineering Physics ITS Event.",
    tech: ["Laravel", "Bootstrap", "SCSS"],
    logo: "epw.png",
    image: null,
    background: "#9BB56D",
    link: null,
  },
  {
    key: "ukmexpo",
    shape: "horizontal",
    name: "UKM Expo ITS",
    description: "Biggest Event by ITS Communities.",
    tech: ["Laravel", "Bootstrap", "SCSS"],
    logo: null,
    image: "ukmexpo.png",
    background: null,
    link: null,
  },
  {
    key: "ilits",
    shape: "box",
    name: "Ini Lho ITS! 2021",
    description: "Biggest Event in ITS Surabaya.",
    tech: ["Laravel", "Bootstrap", "SCSS"],
    logo: "ilits.png",
    image: null,
    background: "#1C2945",
    link: null,
  },
]

export const socialList: SocialListType[] = [
  {
    name: "Instagram",
    detail: "@daffakurniaf11",
    link: "https://www.instagram.com/daffakurniaf11/",
    icon: "instagram",
  },
  {
    name: "WhatsApp",
    detail: "+6285156317473",
    link: "https://wa.me/6285156317473",
    icon: "whatsapp",
  },
  {
    name: "GitHub",
    detail: "@daffakurnia11",
    link: "https://github.com/daffakurnia11",
    icon: "github",
  },
  {
    name: "LinkedIn",
    detail: "Daffa Kurnia Fatah",
    link: "https://www.linkedin.com/in/daffakurniafatah/",
    icon: "linkedin",
  },
];