export const lgLayout = [
  { i: "dafkur2.0", x: 0, y: 0, w: 2, h: 1 },
  { i: "ifem", x: 2, y: 0, w: 1, h: 2 },
  { i: "breakpoint", x: 3, y: 1, w: 1, h: 1 },
  { i: "petrolida", x: 0, y: 1, w: 1, h: 2 },
  { i: "candlecraft", x: 1, y: 1, w: 1, h: 1 },
  { i: "crawlerhub", x: 3, y: 3, w: 2, h: 1 },
  { i: "ecs", x: 3, y: 2, w: 1, h: 1 },
  { i: "spe", x: 1, y: 3, w: 1, h: 1 },
  { i: "epw", x: 0, y: 4, w: 1, h: 1 },
  { i: "ukmexpo", x: 1, y: 4, w: 2, h: 1 },
  { i: "ilits", x: 3, y: 4, w: 1, h: 1 },
];
export const mdLayout = [
  { i: "dafkur2.0", x: 0, y: 0, w: 2, h: 1 },
  { i: "ifem", x: 2, y: 0, w: 1, h: 2 },
  { i: "breakpoint", x: 2, y: 2, w: 1, h: 1 },
  { i: "petrolida", x: 0, y: 1, w: 1, h: 2 },
  { i: "candlecraft", x: 1, y: 1, w: 1, h: 1 },
  { i: "crawlerhub", x: 2, y: 3, w: 2, h: 1 },
  { i: "ecs", x: 0, y: 3, w: 1, h: 1 },
  { i: "spe", x: 1, y: 2, w: 1, h: 1 },
  { i: "epw", x: 2, y: 4, w: 1, h: 1 },
  { i: "ukmexpo", x: 0, y: 4, w: 2, h: 1 },
  { i: "ilits", x: 1, y: 5, w: 1, h: 1 },
];
export const smLayout = [
  { i: "dafkur2.0", x: 0, y: 0, w: 2, h: 1.5 },
  { i: "breakpoint", x: 0, y: 1.5, w: 1, h: 1 },
  { i: "candlecraft", x: 1, y: 1.5, w: 1, h: 1 },
  { i: "ifem", x: 0, y: 2.5, w: 2, h: 3 },
  { i: "crawlerhub", x: 0, y: 6, w: 2, h: 1.5 },
  { i: "ecs", x: 0, y: 8, w: 1, h: 1 },
  { i: "spe", x: 1, y: 8, w: 1, h: 1 },
  { i: "petrolida", x: 0, y: 9, w: 2, h: 3 },
  { i: "ukmexpo", x: 0, y: 12, w: 2, h: 1.5 },
  { i: "epw", x: 0, y: 13.5, w: 1, h: 1 },
  { i: "ilits", x: 1, y: 13.5, w: 1, h: 1 },
];
